name: challenge session
on: 
  push:
    branches:
     - master

jobs:
  Britania_test:
    runs-on: ubuntu-latest
    steps:
     - name: Python Syntax Checker
     - name: date
       run: date   
  # You may pin to the exact commit or the version.
  # uses: cclauss/Find-Python-syntax-errors-action@90f67be9fb626b675a3971b1d08ab29851cb721f
  uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
  Camry_test:
     runs-on: windows-latest
     steps:
      - name: date2
        run: date
  Cut_test: 
     runs-on: macos-latest
     steps:     
       - name: date3
         run: date
  Mirchi_test:
     needs: [Britania_test, Camry_test, Cut_test]  
     runs-on: ubuntu-latest
     steps:
       - id: date4
         run: date
     
