name: challenge session
on: 
  push:
    branches:
     - master

jobs:
  Britania_test:
    runs-on: ubuntu-latest
    steps:
     - name: date
       run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  Camry_test:
     runs-on: windows-latest
     steps:
      - name: date2
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  Cut_test: 
     runs-on: macos-latest
     steps:     
       - name: date3
         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
  Mirchi_test:
     needs: [Britania_test, Camry_test, Cut_test]  
     runs-on: ubuntu-latest
     steps:
       - id: date4
         run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
     
