name: first
on:
   push:
     branches:
       - master
jobs:
  job1: 
     name: First Job1
     runs-on: ubuntu-latest
     steps:
     - name: Step one
       uses: actions/checkout@v2
     - name: Step two
       run: env | sort
       
  
